### ISSUE TITLE
Open/close commands?

### ISSUE THREAD

**Issue by colinl** [drmibell/node-red-contrib-multiple-queue#1]
I want to use this as a simple gate but with control based on topic, so effectively multiple simple gates in parallel, but the `open` and `close` commands do not appear to be available.  Is there a reason they have not been implemented here or is just that they were not considered useful?  I think I can achieve the same thing by rather devious use of the existing commands  but it would be simpler if `open` and `close` were available, as they are on the queue gate.

**[Edit]**  In fact on further consideration I realise that `close` is available as `pause` as that ignores any further messages. 
To achieve the equivalent of `open` operation, with all messages for the topic passing straight through, then I first have to do `resume` followed by `reset`, and then to make sure messages pass straight through I have to follow every message with a `flush` command.  Conveniently the flush is ignored for paused queues so I can just interject a `flush` command after every incoming message, whether that queue is paused or not.

**Comment by colinl** [comment]
Alternatively, perhaps say that setting a max queue size of zero implies that you don't want it to queue at all, and then it drops into simple gate mode using pause and resume to close and open the gates.  Still on a topic by topic basis of course.

**Comment by drmibell** [comment]
There's a lot going on here, so it might be worth backing up to see the big picture. Creating a gate per topic is fundamentally different from creating a queue per topic if we don't know in advance how many topics we will encounter. Queues can be deleted when empty, but gates have to be preserved to handle subsequent messages with the same topic. If new topics keep appearing, you've created a memory leak. It might not bite you often, but it's there. Granted, there are lots of ways for `m-queue` to chew through memory, but they are much easier to handle. There are other technical reasons I didn't try to reproduce all the functionality of `q-gate`, but that's the main one.

**Comment by scantineau** [comment]
Hey ! Two years later but I have the same use case.
I've created a pull request, linked to this https://github.com/drmibell/node-red-contrib-multiple-queue/pull/2

**Comment by colinl** [comment]
Just to say that I don't have a requirement for this any more.

**Comment by drmibell** [comment]
Thanks, @scantineau . This is an interesting approach, if we can avoid the difficulties I mentioned above. I'll close this issue, and we can continue the discussion under your PR.

**Comment by drmibell** [comment]
@colinl - Noted. I'll close this issue but would appreciate if you could comment on the PR.
